# Generated by Django 2.2.4 on 2019-08-28 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField(max_length=2000)),
                ('preparation_process', models.TextField()),
                ('preparation_time', models.DurationField(default=datetime.timedelta)),
                ('number_of_portions', models.PositiveIntegerField(default=1)),
                ('difficulty', models.SmallIntegerField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
